// import localFont from "next/font/local";
import {Vazirmatn} from "next/font/google";
// import { Swiper, SwiperSlide } from 'swiper/react';
import "./globals.css";
import Navbar from "./components/navbar.jsx";
import { Footer } from "./components/footer";

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const vazir = Vazirmatn({
  subsets: ["arabic"],
  weight: ["100","200","300","400","500","600","700","800","900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${vazir.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
